sudo: required

branches:
  only:
    - master

matrix:
  include:
    - dist: trusty
      services:
        - docker
      script:
        - ./build_and_check_linux_wheels.sh
      after_success:
        - ./upload_artifacts_linux.sh
    - os: osx
      osx_image: xcode9.4
      compiler: clang
      script:
        - ./build_mac_os_x_wheels.sh
      after_success:
        - ./upload_artifacts_mac_os_x.sh

install:
  - if [ "${TRAVIS_OS_NAME:-}" == "osx" ]; then ./install_osx.sh; fi

notifications:
  recipients:
    - jb@sqreen.io
    - selim@sqreen.io
