version: '2'
services:
  py_mini_racer_build:
    build:
      context: .
      dockerfile: Dockerfile.build
    image: py_mini_racer.build
    container_name: py_mini_racer.build
  py_mini_racer_py27:
    build:
      context: ./docker
      dockerfile: Dockerfile.py27
  py_mini_racer_py27-narrow:
    build:
      context: ./docker
      dockerfile: Dockerfile.py27-narrow
  py_mini_racer_py35:
    build:
      context: ./docker
      dockerfile: Dockerfile.py35
  py_mini_racer_py34:
    build:
      context: ./docker
      dockerfile: Dockerfile.py34
  py_mini_racer_py36:
    build:
      context: ./docker
      dockerfile: Dockerfile.py36
  py_mini_racer_auditwheel_repair:
    build:
      context: ./docker
      dockerfile: Dockerfile.auditwheel_repair
